feat: asset manager enhancements
vexchange/v3-core pull request #58
Opened 2022-08-15 21:11 UTC by xenide

## Motivation
1. asset should be notified of liquidity addition and removal, so that it can move assets to an optimal allocation 

## Solution
1. please review the draft approach I have proposed over here, and see if it is the direction we want to go
   - in terms of the targeted thresholds for managed / non-managed, we might have need a mapping for each pair 
2. for `burn`, we need to check if we even have enough token for redemption. If not enough, then we need to redeem some tokens from the asset manager to fulfill the request

2022-08-21 21:31 UTC, xenide commented
in terms of optimizations, I was thinking we can collapse the two callback functions into one. 

Besides that, we need to take of the case where burn requires more tokens than available in reserve. But I think we'll take care of this in vexchange/v3-core#98 in another PR

2022-08-22 20:41 UTC, OliverNChalk requested changes
Looks good and clean, some minor comments

2022-08-24 18:18 UTC, OliverNChalk requested changes
Can we do a call to decide on two callbacks vs one?

2022-08-24 19:30 UTC, OliverNChalk approved these changes

2022-08-24 21:25 UTC, merged